version: '3'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: score-front
    restart: always
    ports: 80:3000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: score-api
    restart: always
    expose: 8080

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
    expose: 3306
    environment:
      MYSQL_ROOT_PASSWORD: abcdefghijksaa