version: '3'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: score-front
    restart: always
    ports: 
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: score-api
    restart: always
    expose: 
      - "8080"
    depends_on:
      - "mysql"

  mysql:
    platform: linux/x86_64 
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    expose: 
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: abcdefghijksaa
      EXPLICITe_DEFAULTS_FOR_TIMESTAMP: 1